### ISSUE TITLE
Refactor edit_metadata.js

### ISSUE THREAD

**Issue by hackmastera** [projecthydra/sufia#1473]
Subtasks (consider breaking out into individual issues):

- [ ] location autocomplete needs to be changed to query '/authorities/geonames/location' instead of querying the API directly. As-is, this javascript fails when geonames returns error on username requirement.
- [x] namespace / modularize the code in this file.
- [x] consider moving geonames to questioning authority and adding that as a sufia dependency.

**Comment by hackmastera** [comment]
mjgiarlo: "I know this is 2-3 issues clumped together but giarlo said I should just log this in here now"

**Comment by hackmastera** [comment]
this all got done at some point on sufia 7.
