### ISSUE TITLE
The uploads controller should enable deleting of uploads

### ISSUE THREAD

**Issue by jcoyne** [projecthydra/sufia#1793]
This will allow us to clean up some of the uploads that aren't needed. It won't help us if the user just leaves the page, so we'll still need a method for cleaning up abandoned uploads.

- [ ] Add a delete method to the uploads controller that removes the file and the row in the database
- [ ] Un-hide the `Cancel Upload` button after files are added. It has the effect of triggering a delete/cleanup of all affected files and database rows on the back-end.
- [ ] Make per-file `Cancel` buttons trigger a delete/cleanup of the appropriate file and database row on the back-end.
- [ ] Authorize that the user can delete the upload
- [ ] Send `deleteUrl` in the json response to create.
- [ ] Make the upload form call the delete path when removing:
```
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
```

**Comment by atz** [comment]
If I may broaden the scope here... uploads would benefit from a full RESTful resource endpoint:
- [ ] allow jquery fileuploader to provide functional link (support GET)
- [ ] allow jquery fileuploader to include thumbnail preview image (support related GET)

Authz baseline should be to only the submitting user, since files can be uploaded without a work to attach to, therefore without our more complex modelled permissions.

**Comment by mjgiarlo** [comment]
I'm cool with considering this for 7.1.0.

**Comment by jcoyne** [comment]
Do you really want to provide a thumbnail?  Consider if it's a very large video file.

**Comment by mjgiarlo** [comment]
@atz I'd like to punt those two items to 7.1.0.

**Comment by atz** [comment]
I don't mind punting on thumbnail, but I think that modeling the upload as a proper resource (i.e. having a `resource` rails route) will establish a basis for extension.  It seems like the kind of thing worth doing, even if the front end doesn't make full use of all the routes yet.  That is common enough in rails apps.

**Comment by mjgiarlo** [comment]
I'm inclined to push that to 7.1.0, too, @atz. I'm aiming to push Sufia in the direction of smaller, more frequent releases. (And clearly 7.0.0 is not one of those...)

**Comment by atz** [comment]
How much of this needs to be replicated in the nearly-duplicative but also divergent batch interface?

**Comment by mjgiarlo** [comment]
@atz All of it, AFAIK. Good catch.
