### ISSUE TITLE
Batch uploads controller should enable deleting of uploads

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#1910]
This will allow us to clean up some of the uploads that aren't needed. It won't help us if the user just leaves the page, so we'll still need a method for cleaning up abandoned uploads.

- [ ] Add a delete method to the uploads controller that removes the file and the row in the database
- [ ] Un-hide the `Cancel Upload` button after files are added. It has the effect of triggering a delete/cleanup of all affected files and database rows on the back-end.
- [ ] Make per-file `Cancel` buttons trigger a delete/cleanup of the appropriate file and database row on the back-end.
- [ ] Authorize that the user can delete the upload
- [ ] Send `deleteUrl` in the json response to create.
- [ ] Make the upload form call the delete path when removing:
```
            {% if (file.deleteUrl) { %}
                <button class="btn btn-danger delete" data-type="{%=file.deleteType%}" data-url="{%=file.deleteUrl%}"{% if (file.deleteWithCredentials) { %} data-xhr-fields='{"withCredentials":true}'{% } %}>
                    <i class="glyphicon glyphicon-trash"></i>
                    <span>Delete</span>
                </button>
                <input type="checkbox" name="delete" value="1" class="toggle">
            {% } else { %}
                <button class="btn btn-warning cancel">
                    <i class="glyphicon glyphicon-ban-circle"></i>
                    <span>Cancel</span>
                </button>
            {% } %}
```
### Related work

Refs #1793

**Comment by jcoyne** [comment]
I'm picking nits here, but the BatchUploadsController won't be involved at all.  It's only an interaction between the front-end and the UploadsController.
