### ISSUE TITLE
Support nested works

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2082]
### Descriptive summary

This is an epic ticket wrapping up all tickets related to created arbitrarily nested works in Sufia. Please link other tickets related to this feature below.
- [ ] https://github.com/projecthydra/sufia/issues/1709
- [ ] https://github.com/projecthydra/sufia/issues/1563
- [ ] https://github.com/projecthydra/sufia/issues/1710
- [x] https://github.com/projecthydra/sufia/issues/1861
- [x] https://github.com/projecthydra/sufia/issues/1970
- [x] https://github.com/projecthydra/sufia/issues/2111
- [x] #2197
- [x] #2243

**Comment by mjgiarlo** [comment]
@eliotjordan is interested in this work and how it might connect to existing work in GeoConcerns.

@tpendragon has done some related work in Plum that IIRC will be extracted to CurationConcerns. (We should link that in here once it's ready.)

@vantuyls ping.

**Comment by vantuyls** [comment]
pinging @zhang4952

**Comment by mjgiarlo** [comment]
Closing this epic.
