### ISSUE TITLE
Implement operations functionality and UI

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra/sufia#2571]
# Description

During our first Hydra-in-a-Box work cycle, we added the concept of [operations](https://github.com/projecthydra/curation_concerns/commit/67aa641d957a3812c6456eab504c79635ceb6d3d) to CurationConcerns, and made use of operations to surface more information about the batch create workflow: https://github.com/projecthydra/sufia/commit/bbe69e0cc960819aa9104a371a4a9cab23d29005

An operation is a lightweight wrapper around potentially long-running processes. An operation can be in one of four states:
1. **pending**: the operation has not yet begun
2. **performing**: the operation is being performed
3. **success**: the operation is done and it did what the user expected
4. **failure**: the operation is done and it didn't do what the user expected

An operation can have children operations.
# Subtasks
- [ ] [Background jobs should be wrapped by operations](https://github.com/projecthydra/sufia/issues/2572)
- [ ] [Administrative users should have the ability to manage all operations](https://github.com/projecthydra/sufia/issues/2575)
- [ ] [Dashboard should allow users the ability to list and show operations they created](https://github.com/projecthydra/sufia/issues/2573)
- [ ] [Admin Dashboard should allow the ability to list and show all operations](https://github.com/projecthydra/sufia/issues/2574)
- [ ] [Add logs/status for batch and item level operations](https://github.com/projecthydra/sufia/issues/1779)
